name: Build and Run Tests

on:
  push:
    branches:
      - 'ci_cd'
      - 'develop'
  pull_request:
    branches:
      - 'ci_cd'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Disable analytics
        run: |
            flutter config --no-analytics
            dart --disable-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
